// <auto-generated />
using Embaixadas.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Embaixadas.Migrations
{
    [DbContext(typeof(EmbaixadasContext))]
    [Migration("20220428142730_NewBD")]
    partial class NewBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Embaixadas.Models.Embaixada", b =>
                {
                    b.Property<int>("EmbaixadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmbaixadaEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbaixadaEndereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbaixadaNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbaixadaNumero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmbaixadaId");

                    b.ToTable("Embaixadas");
                });

            modelBuilder.Entity("Embaixadas.Models.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaisCapital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisId");

                    b.ToTable("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
