// <auto-generated />
using Embaixadas.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Embaixadas.Migrations
{
    [DbContext(typeof(EmbaixadasContext))]
    [Migration("20220430232548_AddMoedas")]
    partial class AddMoedas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Embaixadas.Models.Embaixada", b =>
                {
                    b.Property<int>("EmbaixadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmbaixadaEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbaixadaEndereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbaixadaNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbaixadaNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("EmbaixadaId");

                    b.HasIndex("PaisId");

                    b.ToTable("Embaixadas");
                });

            modelBuilder.Entity("Embaixadas.Models.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaisCapital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisMoeda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisId");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Embaixadas.Models.Embaixada", b =>
                {
                    b.HasOne("Embaixadas.Models.Pais", "Pais")
                        .WithMany("Embaixadas")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Embaixadas.Models.Pais", b =>
                {
                    b.Navigation("Embaixadas");
                });
#pragma warning restore 612, 618
        }
    }
}
